### ISSUE TITLE
Towards v1

### ISSUE THREAD

**Issue by makenowjust** [cloudspannerecosystem/memefish#240]
Thanks to @apstndb and others' contributions, this library is more stable and compatible with GoogleSQL. Therefore, it's time to release v1 of memefish.

In doing so, we share some concerns.

- How do we manage `CHANGELOG` or release notes? How is it standard practice in Go?
- More breaking changes to ASTs will probably continue in the future. In that case, would it be convenient for users to bump the major version based on semver?
  * But if not, when should the major version be increased?

**Comment by makenowjust** [comment]
It is hard to release v1 as long as any changes to Spanner would cause breaking changes. We close this issue for now.

**Comment by apstndb** [comment]
My thought:

We shouldn't release v1 because Go modules are strictly required to follow SemVer.
https://go.dev/doc/modules/version-numbers#major-version
memefish can't control Google's release, so we need more breaking changes.

It is better to develop as v0.x.y.
I think there is no blocker of v0.1.0 release.
